apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: healthy-app-rollout
  namespace: argotestapp
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100
  selector:
    matchLabels:
      app: healthy-app
    template:
      metadata:
        labels:
          app: healthy-app
      spec:
        containers:
          - name: healthy-app
            image: quay.io/rhn-support-ccostell/test-training/healthy-app:latest
            ports:
              - containerPort: 8080
            readinessProbe:
                httpGet:
                  path: /health
                  port: 8080
                initialDelaySeconds: 5
                periodSeconds: 10