apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate-analysis
  namespace: argo-rollouts
spec:
  args:
  - name: api-token
    valueFrom:
      secretKeyRef:
        key: token
        name: secret-sa-token # argo-rollouts-token
  metrics:
  - count: 5
    failureCondition: result[0] < 0.05
    interval: 30s
    name: error-rate-analysis
    provider:
      prometheus:
        address: https://prometheus-k8s.openshift-monitoring.svc.cluster.local:9091/ 
        authentication:
          sigv4: {}
        headers:
        - key: Authorization
          value: Bearer {{args.api-token}}
        insecure: true
        query: |
          sum(haproxy_backend_http_responses_total{exported_namespace='argo-rollouts', route="route-rollouts-example", code!="5**"})
    successCondition: len(result) == 0 || result[0] >= 0.95
