apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate-analysis
  namespace: argo-rollouts
spec:
  metrics:
    - name: error-rate
      interval: 30s
      count: 5
      successCondition: len(result) == 0 || result[0] >= 0.95
      failureCondition: result[0] < 0.05
      provider:
        prometheus:
          address: https://prometheus-k8s.openshift-monitoring.svc.cluster.local:9091
          insecureSkipVerify: true
          tlsConfig:
            caFile: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
