apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: argo-rollouts
  name: argo-rollouts-rolebinding
subjects:
  - kind: ServiceAccount
    name: argo-rollouts
    namespace: argo-rollouts
roleRef:
  kind: Role
  name: argo-rollouts-role
  apiGroup: rbac.authorization.k8s.io
