apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-rollouts-namespace-binding
  namespace: argo-rollouts # argotestapp
subjects:
  - kind: ServiceAccount
    name: argo-rollouts
    namespace: argo-rollouts # argotestapp
roleRef:
  kind: Role
  name: argo-rollouts-namespace-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-rollouts-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-rollouts-cluster-role
subjects:
  - kind: ServiceAccount
    name: argo-rollouts
    namespace: argo-rollouts

