apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-rollouts-namespace-binding
  namespace: argotestapp
subjects:
  - kind: ServiceAccount
    name: argo-rollouts
    namespace: argotestapp
roleRef:
  kind: Role
  name: argo-rollouts-namespace-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-rollouts-cluster-binding
subjects:
  - kind: ServiceAccount
    name: argo-rollouts
    namespace: argotestapp
roleRef:
  kind: ClusterRole
  name: argo-rollouts-cluster-role
  apiGroup: rbac.authorization.k8s.io
