apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-rollouts-leases-binding
  namespace: argo-rollouts # argotestapp
subjects:
  - kind: ServiceAccount
    name: argo-rollouts
    namespace: argotestapp
roleRef:
  kind: Role
  name: argo-rollouts-leases
  apiGroup: rbac.authorization.k8s.io