apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argotestapp
  name: argo-rollouts-configmap-access
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]