apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-rollouts-configmap-access-binding
  namespace: argotestapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-rollouts-configmap-access
subjects:
  - kind: ServiceAccount
    name: argo-rollouts
    namespace: argotestapp