kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-api-access-binding
  namespace: openshift-monitoring
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
roleRef:
  kind: Role
  name: prometheus-api-access
  apiGroup: rbac.authorization.k8s.io
