apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: openshift-monitoring
  name: prometheus-query-access
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["prometheuses"]
  verbs: ["get", "list", "watch"]
