kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-rollouts-prometheus-access
subjects:
  - kind: ServiceAccount
    name: argo-rollouts
    namespace: argo-rollouts
roleRef:
  kind: ClusterRole
  name: prometheus-api-access
  apiGroup: rbac.authorization.k8s.io
