kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-api-access
  namespace: openshift-monitoring
rules:
  - apiGroups: 
    - ""
    resources: 
    - "services"
    - "endpoints"
    verbs: 
    - "get"
    - "list"
    - "watch"