apiVersion: v1
kind: Service
metadata:
  labels:
    app: error-app
  name: error-app
  namespace: argo-rollouts # argotestapp
spec:
  selector:
    app: error-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: metrics # web

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
  name: route-rollouts-example
  namespace: argo-rollouts
spec:
  host: route-rollouts-example-argo-rollouts.<ingress-domain> # ingress domain as a variable
  path: /health
  port:
    targetPort: metrics
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: error-app
    weight: 100
  wildcardPolicy: None
