# Apply this first

# namespace

apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts

--- 

# subscription

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
spec:
  channel: latest 
  installPlanApproval: Automatic
  name: openshift-gitops-operator 
  source: redhat-operators 
  sourceNamespace: openshift-marketplace 
  startingCSV: openshift-gitops-operator.v1.14.2
  config:
    env:
      - name: NAMESPACE_SCOPED_ARGO_ROLLOUTS
        value: "true"

---

# rollout manager

apiVersion: argoproj.io/v1alpha1
kind: RolloutManager
metadata:
  name: argo-rollout-rm
  namespace: argo-rollouts
  labels:
    example: basic
spec: 
  namespaceScoped: true